twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: '%env(default:Europe/Warsaw:APP_TIMEZONE)%'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Twig\Extra\Intl\IntlExtension: ~
    Twig\Extra\String\StringExtension: ~

when@test_cached:
    twig:
        strict_variables: true
